// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FooterMusic: typeof import('./src/components/ItemMusic/FooterMusic.vue')['default']
    IconList: typeof import('./src/components/Home/IconList.vue')['default']
    ItemList: typeof import('./src/components/ItemList.vue')['default']
    ItemMusicList: typeof import('./src/components/ItemMusic/ItemMusicList.vue')['default']
    ItemMusicTop: typeof import('./src/components/ItemMusic/ItemMusicTop.vue')['default']
    MusicDetail: typeof import('./src/components/MusicDetail/index.vue')['default']
    MusicList: typeof import('./src/components/Home/MusicList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperTop: typeof import('./src/components/Home/SwiperTop.vue')['default']
    TopNav: typeof import('./src/components/Home/TopNav.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
